field: 2c12c66f-f886-4632-942c-5b4bcf3dee30 # Article Body
fieldLayouts:
  82e5d2c4-7eab-4b8e-8538-fa8864770475:
    tabs:
      -
        elements:
          -
            fieldUid: 6d08def2-e449-4afb-a69f-7721aec3e6d9 # oEmbed Media
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 832efb09-f00b-4129-a3cc-2b8315b2b1ec # oEmbed Media Title
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 98ea29a1-74bd-46fc-a285-e93fce47c2c7 # oEmbed Media Link
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6d08def2-e449-4afb-a69f-7721aec3e6d9: # oEmbed Media
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: oembedMedia
    instructions: ''
    name: 'oEmbed Media'
    searchable: true
    settings:
      url: ''
    translationKeyFormat: null
    translationMethod: none
    type: wrav\oembed\fields\OembedField
  98ea29a1-74bd-46fc-a285-e93fce47c2c7: # oEmbed Media Link
    columnSuffix: null
    contentColumnType: string(1020)
    fieldGroup: null
    handle: oembedMediaLink
    instructions: ''
    name: 'oEmbed Media Link'
    searchable: true
    settings:
      byteLimit: null
      charLimit: 255
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  832efb09-f00b-4129-a3cc-2b8315b2b1ec: # oEmbed Media Title
    columnSuffix: null
    contentColumnType: string(1020)
    fieldGroup: null
    handle: oembedMediaTitle
    instructions: ''
    name: 'oEmbed Media Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: 255
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: oembedMediaBlock
name: 'oEmbed Media Block'
sortOrder: 5
