field: 2c12c66f-f886-4632-942c-5b4bcf3dee30 # Article Body
fieldLayouts:
  35033d33-2975-4a13-b77a-4771dbf75225:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0a731147-6b21-43a1-98e6-b4a023ee0465 # Section Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3a41a6c-bf71-419a-a57d-b58176756e4b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 79e741cf-5272-4f48-b3ed-84e4360b5fd2 # Section Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9001ff2-4858-486f-8d2f-a37d103cb456
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 014896df-c8f7-47c3-abea-03dbec440413 # Section Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32ed1a72-23ef-4a1f-aa82-082e3e3c58f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d5ccef14-4f83-4c82-bcb4-724fa51aa009
        userCondition: null
fields:
  0a731147-6b21-43a1-98e6-b4a023ee0465: # Section Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: sectionHeading
    instructions: null
    name: 'Section Heading'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  79e741cf-5272-4f48-b3ed-84e4360b5fd2: # Section Summary
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: sectionSummary
    instructions: null
    name: 'Section Summary'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  014896df-c8f7-47c3-abea-03dbec440413: # Section Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sectionImage
    instructions: null
    name: 'Section Image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:c2e619ef-2739-46b9-b26c-78d421566532' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c2e619ef-2739-46b9-b26c-78d421566532' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: sectionBlock
name: 'Section Block'
sortOrder: 8
