fieldLayouts:
  f8dc1e43-311f-44d1-b80c-95d185e6a357:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 060a797f-1e4e-4c87-923a-2bee339685c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5391bc87-d5d4-443f-8335-704b11e20b5f # Featured Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae8c3f16-20c2-4de3-912c-d3a429ba60a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9c7490c0-1024-46b3-99a2-23a58c04c550 # Lede
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b59b3c32-e9c3-46b0-a47f-b4b414e278fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fd18d1cb-d224-448e-8d13-c36f3387c611 # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e94f2d67-ad29-49e6-a42c-918cda79baea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed999e25-ff72-4caf-95c7-dc3821d2642f # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9858e4ff-a136-48a8-ac06-aabc2b057f74
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: da96a334-cfc3-43e7-a41f-3bd516cfbd4e # Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2699876e-d512-417e-98f5-0b0b7c0f36bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7299e97d-1b84-46a5-96be-de9062d0dd4e # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47b094ba-bbd2-47fd-a195-df7dcd2dfcf5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2c12c66f-f886-4632-942c-5b4bcf3dee30 # Article Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f32a19d1-874b-458e-b5fe-d4b91f0966c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a101802d-d3cc-4719-9415-cabcef3150ad # Wysiwyg Editor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 101660dd-2350-4bbb-ba5e-5f439f12241f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5dfc3df6-d95a-4b06-af65-f376625c5700 # Related Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 955ec072-7620-4852-948a-be8a0031f6f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c56ecf3e-0e59-4033-8b25-33b8a3bad3f8 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c68d8f39-d5ba-4313-b643-7d8f1c11f55e
            userCondition: null
            warning: null
            width: 100
        name: Article
        uid: 10312368-2f8d-4303-9617-c664520b4c95
        userCondition: null
handle: articles
hasTitleField: true
name: Articles
section: 530c73e4-c186-4ba2-bd9f-9e301383b88e # Articles
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
