color: null
fieldLayouts:
  4ada5c7c-59f2-400a-8791-bc7a8e09a57a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ad86474e-0b81-409b-9ea9-b62fc22b6858
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f6b8de39-72e6-457f-acf4-734b91e52182 # Article Body - Code - Code
            handle: null
            includeInCards: true
            instructions: null
            label: Code
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a02d97d0-8313-4b3d-acb4-e14f1eaac2ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ca134d3b-9a07-4a31-a00f-f3c2d1db702e # Article Body - Code - Languages
            handle: null
            includeInCards: false
            instructions: null
            label: Languages
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0ac74e3-1bef-4dac-a784-29038fa50705
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7ec485c5-0df8-49c9-93b2-2a9658d6edd4 # Article Body - Code - Caption
            handle: null
            includeInCards: false
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9deadcc8-e19f-4852-a69a-4ad10594f510
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89eba528-c391-494e-8ee0-67787274f255 # Article Body - Code - Link
            handle: null
            includeInCards: false
            instructions: null
            label: Link
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29b47f8f-18ce-49ca-b575-f3cc5ecb3116
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: abed0708-a478-43fe-8e20-afe552d53fc1
        userCondition: null
handle: code
hasTitleField: false
icon: null
name: Code
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
