fieldLayouts:
  1d35bb52-2006-4bb6-89f1-4a11c343155d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4715f226-1b96-4903-9cad-e3f6bec1ea8f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cd333917-1208-4c9a-a96b-3ff2bdfbaed9 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 781e34cd-7cba-4c75-8a2f-0ecb0bba6db7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3cecc149-fd4c-49c4-9e8a-2aa6e3d0a323 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93fe0732-2abf-4dbf-bb48-116658715372
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 959dff9f-9403-4943-8efc-69c8db5fa65c # SVG
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c1a0d9e-8587-419b-9626-00e7301b41db
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9c7490c0-1024-46b3-99a2-23a58c04c550 # Lede
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4319a9a1-5c18-4b26-8943-8b3bc841df14
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7299e97d-1b84-46a5-96be-de9062d0dd4e # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7b59df0-ac6b-4e21-b7f6-8c69f5846869
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 593ae0b4-d44a-428f-8c8e-5dc4d4b7bd6b # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06164594-1d94-4239-9fd4-decf66aea98d
            userCondition: null
            warning: null
            width: 100
        name: Home
        uid: 34fbc5a9-a12a-489e-870b-c83433a62d18
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: c6acf41a-56e6-41a0-946e-b1795c2c7b74 # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
