color: null
fieldLayouts:
  edabdc8a-57e8-41cb-9b9a-d8361f9d0bee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 40cbbde4-37f6-4ee7-b533-e2bb9db0b1f1
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe815f3d-a3a6-42b3-9d34-5de9055110b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 178afcda-33ec-4f50-8f65-0135132f98a4
            handle: null
            includeInCards: true
            instructions: null
            label: 'Image Type'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe651867-c744-4a79-b930-8897d3cf2a16
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 99a4c10e-65c3-4e9d-9750-3cc9901141ed
            handle: null
            includeInCards: false
            instructions: null
            label: imagePosition
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1e14d9b-8cf0-421d-aedf-13a8f549c735
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: edbdd24e-9d2d-4df8-a8ca-2e2002dc15a7 # Article Body - Image - Caption
            handle: imageCaption
            includeInCards: false
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 559ed6d2-1ac4-4e64-a4a3-15074f360d2f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e7488985-ca55-4f73-84c2-a6f182cdb2f4
            handle: null
            includeInCards: false
            instructions: null
            label: 'Caption Position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dbb8d0e-b46d-4600-b965-fb24357c9fba
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3a19da49-8001-43cb-9449-df42465380c7
        userCondition: null
handle: image
hasTitleField: false
icon: null
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
