fieldLayouts:
  79bd0750-bc6f-486e-97d4-2100f5eae470:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bec670e2-6317-43cb-b19b-f35b641b59f2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5391bc87-d5d4-443f-8335-704b11e20b5f # Featured Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4749d57-9131-408f-87a7-0e0ca0373675
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbeb3bcd-1df7-4c6a-8135-3ce48fbab77c # Hyperlink
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f4d9108-05c4-41b9-95dc-0f19d115aa04
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9c7490c0-1024-46b3-99a2-23a58c04c550 # Lede
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89e4553b-f90a-43ce-bd5e-a786dda9d324
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc6e35f3-4a2a-4b55-ae4a-717059ff4104 # Note
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53852c7f-5fa5-4fa3-ae60-341a439d6842
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: da96a334-cfc3-43e7-a41f-3bd516cfbd4e # Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9723c172-920b-473d-b9bf-f9445c3bd6e8
            userCondition: null
            warning: null
            width: 100
        name: 'Link Layout'
        uid: 8259df5e-7ddf-44c7-b1a3-e048ebc9f871
        userCondition: null
handle: links
hasTitleField: true
name: Links
section: a1a12949-11a6-4002-b9fd-11bec4a22eba # Links
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
