fieldLayouts:
  5a11463d-06ba-4da2-983e-bf1240595311:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6204f9c3-d76a-4ab1-87c6-061491839742
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5391bc87-d5d4-443f-8335-704b11e20b5f # Featured Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e77c16a6-e7e8-4bf0-b820-15d1425ec937
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc6e35f3-4a2a-4b55-ae4a-717059ff4104 # Note
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 968039e6-8bad-489e-94f2-1fefc8bec455
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbeb3bcd-1df7-4c6a-8135-3ce48fbab77c # Hyperlink
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5de544d3-3cfa-4f16-84b9-3a16c3e227b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: da96a334-cfc3-43e7-a41f-3bd516cfbd4e # Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d74078d6-c65e-4aab-8e8e-79a5e1c34330
            userCondition: null
            warning: null
            width: 100
        name: Note
        uid: b20073a7-e6d0-477d-8a74-e273f433faae
        userCondition: null
handle: notes
hasTitleField: true
name: Notes
section: b00f9752-ea7e-435b-990d-61505b8e35bc # Notes
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
