color: null
fieldLayouts:
  82e5d2c4-7eab-4b8e-8538-fa8864770475:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6d08def2-e449-4afb-a69f-7721aec3e6d9
            handle: null
            includeInCards: false
            instructions: null
            label: 'oEmbed Media'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05f54939-80c5-4f62-92c6-7032d9f06d2d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 832efb09-f00b-4129-a3cc-2b8315b2b1ec
            handle: null
            includeInCards: true
            instructions: null
            label: 'oEmbed Media Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb72cb83-e638-4ec5-8f39-779c2bf71a5e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 98ea29a1-74bd-46fc-a285-e93fce47c2c7
            handle: null
            includeInCards: false
            instructions: null
            label: 'oEmbed Media Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0513cb51-6fbd-4d26-a4e2-cab2b09ca487
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a668c335-9446-4b9c-a788-f7acce2e6986
        userCondition: null
handle: oembedMediaBlock
hasTitleField: false
icon: null
name: 'oEmbed Media Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
