color: null
fieldLayouts:
  82e5d2c4-7eab-4b8e-8538-fa8864770475:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 629a3b1d-f47d-46f0-aea5-e5d2173ed767
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a668c335-9446-4b9c-a788-f7acce2e6986
        userCondition: null
handle: oembedMediaBlock
hasTitleField: false
icon: null
name: 'oEmbed Media Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
