color: null
fieldLayouts:
  f784387a-935d-4adf-a1cd-097d9af3bd61:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9c6859bd-de12-4ed2-8570-719a1b29df55
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a3f7c83c-c06b-4c12-996f-89cfac195f23 # Article Body - Pull Quote - pullQuote
            handle: null
            includeInCards: true
            instructions: null
            label: pullQuote
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f578ce14-4c65-406a-be00-b2c28a9563c4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2fe9c488-ec49-4501-94b4-68725afc8c04 # Article Body - Pull Quote - Position
            handle: null
            includeInCards: false
            instructions: null
            label: Position
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbc854bc-e3ea-45f1-b9b6-ec559b8431d9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cb1445cb-5794-4a6e-ae1f-ecee9b08fc15
        userCondition: null
handle: pullQuote
hasTitleField: false
icon: null
name: 'Pull Quote'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
