fieldLayouts:
  28afc0d2-b5fd-438f-9aac-df9a27a2ac6b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e1a6c632-967c-4a01-bc32-a8b3b1567da6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 959dff9f-9403-4943-8efc-69c8db5fa65c # SVG
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 550748f7-d340-4038-9410-3d706b2288b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b642035e-5f77-4f22-bb9f-060720ddae95 # Chinese
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6f8f4e5-7fc9-4ccc-a17c-79a0aeaaa601
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fcdccecf-de72-4e6f-ab6b-df87f08f7622 # English
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c56f7ffa-1e40-42ec-82ab-055528666e85
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4484103a-3c36-4f70-94d2-e8c97abba2ed # Pinyin
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aeecdbca-5e38-4394-ba23-86d3d17decec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9c7490c0-1024-46b3-99a2-23a58c04c550 # Lede
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6eb97617-8446-4bb1-815c-67309a0ca9eb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7299e97d-1b84-46a5-96be-de9062d0dd4e # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e42c2fd0-c788-4cc1-928f-087772b5e0b5
            userCondition: null
            warning: null
            width: 100
        name: 'Chinese Zodiac'
        uid: 68e5580b-ff2e-40a3-a330-c9bd3065f9b2
        userCondition: null
handle: shengxiao
hasTitleField: false
name: 生肖
section: 8bf050bc-0e15-47bc-9f8c-af669c632ed5 # 生肖
sortOrder: 1
titleFormat: '{english}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
