defaultPlacement: end
fieldLayouts:
  e89b9215-dc74-404b-8d79-229d3b462a4a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 12b1a439-2f32-4adb-8d32-5c03e3bd1438
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ba8a3f3-9fcd-4f7f-9820-6763cbf76c50 # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cb7f8ff-bdb6-4b91-b806-e920699f48dd
            userCondition: null
            warning: null
            width: 100
        name: Tags
        uid: 9d05a064-f3fe-4c96-9d2e-8c27229e1317
        userCondition: null
handle: tags
name: Tags
siteSettings:
  840ad40c-34ac-4597-8c5f-747198813889: # Scott Gruber
    hasUrls: true
    template: tags/_entry
    uriFormat: 'tags/{slug}'
structure:
  maxLevels: 2
  uid: 9b9756b6-1fe1-4edc-9fea-698010f3a734
