fieldLayouts:
  20d7ea6a-3c9b-48b0-bc46-8c3023bdb13f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2d0cebf3-2efd-4f6f-9582-433b39788b73
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8bc926ad-dd9d-4c60-bee2-9f4ebe13799c
        userCondition: null
fs: files
handle: files
name: Files
sortOrder: 7
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
