fieldLayouts:
  668cc435-eebf-4d25-8b76-c3a6bbd96a58:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 40569be1-aeb8-4a4d-aef6-47132aa90858
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9f81a782-b076-48d8-a3b7-76ac02f1554b
        userCondition: null
fs: icons
handle: icons
name: Icons
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
