fieldLayouts:
  668cc435-eebf-4d25-8b76-c3a6bbd96a58:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fs: icons
handle: icons
hasUrls: true
name: Icons
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: '@assetUrl/icons'
