fieldLayouts:
  1aa3226d-2557-4588-8f14-75cd8bada136:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: 25c53ff5-01c2-4622-af2a-55a82fc8236f # Image Alt
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 787a38f7-dc31-4bf9-88d0-ddca37022b49 # Image Caption
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Images
        sortOrder: 1
fs: images
handle: images
hasUrls: true
name: Images
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: '@assetUrl/images'
