fieldLayouts:
  a232d024-4494-4554-b390-4c443dd2936e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b865e495-c5a8-4c4f-903c-bbb9ac24cfc7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 25c53ff5-01c2-4622-af2a-55a82fc8236f # Image Alt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8be0ae3a-ec5b-4c17-8c79-e77d1533f837
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 787a38f7-dc31-4bf9-88d0-ddca37022b49 # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5620d58-116f-4e7e-84c2-a55d4238ef85
            userCondition: null
            warning: null
            width: 100
        name: Vectors
        uid: 8f10ae9c-4312-48ec-889d-87585e39720d
        userCondition: null
fs: vectors
handle: vectors
name: Vectors
sortOrder: 6
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
