columnSuffix: null
contentColumnType: string
fieldGroup: 80392b7c-eb61-48f1-a844-52382d42d4d0 # Article
handle: articleBody
instructions: null
name: 'Article Body'
searchable: true
settings:
  contentTable: '{{%matrixcontent_articlebody}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
