columnSuffix: null
handle: captionPosition
instructions: null
name: 'Article Body - Image - Caption Position'
searchable: true
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Block Start'
        -
          - value
          - blockStart
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Block End'
        -
          - value
          - blockEnd
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Inset Start'
        -
          - value
          - insetStart
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Inset End'
        -
          - value
          - insetEnd
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
