columnSuffix: null
contentColumnType: string(1020)
handle: chinese
instructions: 中文
name: Chinese
searchable: true
settings:
  byteLimit: null
  charLimit: 255
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
