columnSuffix: null
handle: codeLanguage
instructions: 'What code language are you using?'
name: 'Article Body - Code - Languages'
searchable: true
settings:
  options:
    -
      __assoc__:
        -
          - label
          - CSS
        -
          - value
          - css
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - HTML
        -
          - value
          - markup
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - JavaScript
        -
          - value
          - javascript
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - JSON
        -
          - value
          - json
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - PHP
        -
          - value
          - php
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Python
        -
          - value
          - python
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Bash + Shell'
        -
          - value
          - bash
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - GraphQL
        -
          - value
          - graphql
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Git
        -
          - value
          - git
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Twig
        -
          - value
          - twig
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
