columnSuffix: null
handle: code
instructions: 'Paste in HTML Snippets'
name: 'Article Body - Code - Code'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
