columnSuffix: null
handle: formatedText
instructions: null
name: 'Article Body - CKEditor - Text'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: ad5de9df-9be4-40a7-b281-82f1df1cbe55 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
