columnSuffix: null
handle: hyperlink
instructions: null
name: Hyperlink
searchable: true
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
