columnSuffix: null
contentColumnType: string(255)
fieldGroup: 0b0b084d-d2d9-430c-a3fe-88c9449e57c8 # Common
handle: hyperlink
instructions: ''
name: Hyperlink
searchable: true
settings:
  maxLength: '255'
  placeholder: ''
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
