columnSuffix: null
contentColumnType: text
fieldGroup: c78e89ad-d2df-43dc-8129-05abe236e92b # Media
handle: imageCaption
instructions: ''
name: 'Image Caption'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
