columnSuffix: null
contentColumnType: text
fieldGroup: c78e89ad-d2df-43dc-8129-05abe236e92b # Media
handle: imageAlt
instructions: 'Alt text for images'
name: 'Image Alt'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
