columnSuffix: null
contentColumnType: string
fieldGroup: 22c9420c-33b2-4619-93ac-0e1870c65fe3 # Language
handle: language
instructions: null
name: Language
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - 简体字
        -
          - value
          - zh-Hans
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 繁体字
        -
          - value
          - zh-Hant
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'American English'
        -
          - value
          - en-US
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Pinyin
        -
          - value
          - zh-Latn-pinyin
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
