columnSuffix: null
handle: lede
instructions: 'A lede paragraph should emphasize grabbing the attention of the reader i.e. "don''t bury the lede".'
name: Lede
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
