columnSuffix: null
contentColumnType: string(640)
handle: metaDescription
instructions: null
name: 'Meta Description'
searchable: true
settings:
  byteLimit: null
  charLimit: 160
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Need help to make your site accessible, fast and look good? Ask Scott.'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
