columnSuffix: null
handle: note
instructions: null
name: Note
searchable: true
settings:
  byteLimit: null
  charLimit: 800
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
