columnSuffix: null
handle: sectionSummary
instructions: null
name: 'Article Body - Section Block - Section Summary'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: ad5de9df-9be4-40a7-b281-82f1df1cbe55 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
