columnSuffix: null
contentColumnType: string(1020)
fieldGroup: bb54b5cc-a6f1-4445-97ab-422838895d39 # Globals
handle: siteDescription
instructions: ''
name: 'Site Description'
searchable: true
settings:
  byteLimit: null
  charLimit: 255
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
