columnSuffix: null
contentColumnType: string(400)
fieldGroup: bb54b5cc-a6f1-4445-97ab-422838895d39 # Globals
handle: siteAuthor
instructions: null
name: 'Site Author'
searchable: true
settings:
  byteLimit: null
  charLimit: 100
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
