columnSuffix: null
contentColumnType: text
handle: summary
instructions: 'Provide a short summary or description to use when entry is a featured story or on a list page.'
name: Summary
searchable: true
settings:
  byteLimit: null
  charLimit: 280
  code: false
  columnType: null
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
