columnSuffix: null
contentColumnType: string
fieldGroup: 4cacf4e4-44a6-4fb2-8afb-805e1aed82a6 # Meta
handle: tags
instructions: null
name: Tags
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:febbbd03-74e4-49e4-ba70-2a10660683f1' # Tags
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
