dateModified: 1733417949
email:
  fromEmail: scott@scottgruber.me
  fromName: 'Scott Gruber'
  replyToEmail: scott@scottgruber.me
  template: null
  transportSettings:
    token: 2d16c84c-6aa6-4087-8f3c-462e760fb29d
  transportType: craftcms\postmark\Adapter
fs:
  files:
    hasUrls: true
    name: Files
    settings:
      path: '@assetUrl/files'
    type: craft\fs\Local
    url: '@assetUrl/files'
  icons:
    hasUrls: true
    name: Icons
    settings:
      path: '@assetPath/icons'
    type: craft\fs\Local
    url: '@assetUrl/icons'
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@assetPath/images'
    type: craft\fs\Local
    url: '@assetUrl/images'
  vectors:
    hasUrls: true
    name: Vectors
    settings:
      path: '@assetPath/vectors'
    type: craft\fs\Local
    url: '@assetUrl/vectors'
meta:
  __names__:
    0a731147-6b21-43a1-98e6-b4a023ee0465: 'Article Body - Section Block - Section Heading' # Article Body - Section Block - Section Heading
    001cafe4-9951-4d9f-bb8c-3be27a274d25: 'Markdown Editor' # Markdown Editor
    2a0986db-1e27-4728-8cf7-1132b9ff6b9a: Links # Links
    2c12c66f-f886-4632-942c-5b4bcf3dee30: 'Article Body' # Article Body
    2fe9c488-ec49-4501-94b4-68725afc8c04: 'Article Body - Pull Quote - Position' # Article Body - Pull Quote - Position
    3cecc149-fd4c-49c4-9e8a-2aa6e3d0a323: 'Hero Image' # Hero Image
    3ecc443a-7ed5-434b-a4b7-c2c2d23a9746: Files # Files
    4b6b6d6c-81b4-4b24-bdef-3776bcc7bcfd: Language # Language
    5aea0788-becb-46c2-96c8-75768b9f40ea: 'Article Body - Markdown Editor - Text' # Article Body - Markdown Editor - Text
    5dfc3df6-d95a-4b06-af65-f376625c5700: 'Related Entries' # Related Entries
    7ec485c5-0df8-49c9-93b2-2a9658d6edd4: 'Article Body - Code - Caption' # Article Body - Code - Caption
    8bf050bc-0e15-47bc-9f8c-af669c632ed5: 生肖 # 生肖
    9ba8a3f3-9fcd-4f7f-9820-6763cbf76c50: Icon # Icon
    9c7490c0-1024-46b3-99a2-23a58c04c550: Lede # Lede
    22f5d0ea-4b7c-4b3c-a8d6-2b353b92b0c6: Code # Code
    25c53ff5-01c2-4622-af2a-55a82fc8236f: 'Image Alt' # Image Alt
    40cbbde4-37f6-4ee7-b533-e2bb9db0b1f1: 'Article Body - Image - Image' # Article Body - Image - Image
    048a11fd-1d26-4b42-b9a0-f37553779e58: 'Article Body - Quote - Attribution' # Article Body - Quote - Attribution
    69ae30b5-6749-4f94-9283-63027e64b000: 'Site Author Email' # Site Author Email
    79e741cf-5272-4f48-b3ed-84e4360b5fd2: 'Article Body - Section Block - Section Summary' # Article Body - Section Block - Section Summary
    81e0d769-aaa3-4b7f-aca5-734aaa9b17e5: Image # Image
    84d12d2d-7545-49a2-9888-40ee29c755ec: 'oEmbed Media Block' # oEmbed Media Block
    88e56014-9326-428a-b6b1-4852e93186dd: 'Article Body - CKEditor - Text' # Article Body - CKEditor - Text
    89eba528-c391-494e-8ee0-67787274f255: 'Article Body - Code - Link' # Article Body - Code - Link
    90e1e15c-f3ec-4522-999d-401ffa0bcfbb: 'Site Author' # Site Author
    99a4c10e-65c3-4e9d-9750-3cc9901141ed: 'Article Body - Image - imagePosition' # Article Body - Image - imagePosition
    178afcda-33ec-4f50-8f65-0135132f98a4: 'Article Body - Image - Image Type' # Article Body - Image - Image Type
    188d75c9-c3ea-42e5-b60d-6bfb7989d581: scottgruber.me # scottgruber.me
    230b8c18-409b-4c42-93d8-be7c54f3adc0: 'Article Body - Quote - Quote' # Article Body - Quote - Quote
    354dc212-5598-4653-b85c-2039e9d25a78: Icons # Icons
    530c73e4-c186-4ba2-bd9f-9e301383b88e: Articles # Articles
    537fe772-9a3a-44d4-b202-8ca50553e9f6: Quote # Quote
    593ae0b4-d44a-428f-8c8e-5dc4d4b7bd6b: 'Meta Description' # Meta Description
    677cdf09-801c-4e50-bbc4-e1781cc4a516: Articles # Articles
    726f9846-f62f-4d4a-900c-de38bf7071ec: 'Page Layout' # Page Layout
    787a38f7-dc31-4bf9-88d0-ddca37022b49: 'Image Caption' # Image Caption
    840ad40c-34ac-4597-8c5f-747198813889: 'Scott Gruber' # Scott Gruber
    924a5c20-68b5-410b-9f04-1a110c403658: Home # Home
    959dff9f-9403-4943-8efc-69c8db5fa65c: SVG # SVG
    4397f088-eb6d-418b-be6f-73dbea513e60: 'Section Block' # Section Block
    5391bc87-d5d4-443f-8335-704b11e20b5f: 'Featured Entry' # Featured Entry
    7299e97d-1b84-46a5-96be-de9062d0dd4e: Body # Body
    014896df-c8f7-47c3-abea-03dbec440413: 'Article Body - Section Block - Section Image' # Article Body - Section Block - Section Image
    64214bae-d1c1-4b72-bb81-6eb2195039fe: 'Pull Quote' # Pull Quote
    4484103a-3c36-4f70-94d2-e8c97abba2ed: Pinyin # Pinyin
    50556672-532a-42dc-986b-aee577c6ef78: CKEditor # CKEditor
    a1a12949-11a6-4002-b9fd-11bec4a22eba: Links # Links
    a3f7c83c-c06b-4c12-996f-89cfac195f23: 'Article Body - Pull Quote - pullQuote' # Article Body - Pull Quote - pullQuote
    a33f4dc4-20ca-4cdc-95e6-25819f455342: Now # Now
    a913e819-b557-409a-9eed-370c9a138d23: 生肖 # 生肖
    a101802d-d3cc-4719-9415-cabcef3150ad: 'Wysiwyg Editor' # Wysiwyg Editor
    ad5de9df-9be4-40a7-b281-82f1df1cbe55: Simple # Simple
    afc084fc-aa87-46da-b9b5-d8ef18d375bf: Now # Now
    b00f9752-ea7e-435b-990d-61505b8e35bc: Notes # Notes
    b0437cce-f374-4fae-b82f-d4afc4843678: Vectors # Vectors
    b642035e-5f77-4f22-bb9f-060720ddae95: Chinese # Chinese
    c2e619ef-2739-46b9-b26c-78d421566532: Images # Images
    c6acf41a-56e6-41a0-946e-b1795c2c7b74: Home # Home
    c46fe660-d362-46c7-be65-3695ca76bf3a: '300 Square' # 300 Square
    c56ecf3e-0e59-4033-8b25-33b8a3bad3f8: Summary # Summary
    ca134d3b-9a07-4a31-a00f-f3c2d1db702e: 'Article Body - Code - Languages' # Article Body - Code - Languages
    cc5eb26e-99ce-4fcc-ab16-72ec1b7c00d2: 'Public Schema' # Public Schema
    cd333917-1208-4c9a-a96b-3ff2bdfbaed9: Heading # Heading
    ce9c5925-d13e-4248-8980-3683d854c4d4: Notes # Notes
    da96a334-cfc3-43e7-a41f-3bd516cfbd4e: Tags # Tags
    dbeb3bcd-1df7-4c6a-8135-3ce48fbab77c: Hyperlink # Hyperlink
    e6a58602-4fcb-4319-a14c-053d4b9fd671: 'Site Description' # Site Description
    e7488985-ca55-4f73-84c2-a6f182cdb2f4: 'Article Body - Image - Caption Position' # Article Body - Image - Caption Position
    ed999e25-ff72-4caf-95c7-dc3821d2642f: Image # Image
    edbdd24e-9d2d-4df8-a8ca-2e2002dc15a7: 'Article Body - Image - Caption' # Article Body - Image - Caption
    f6b8de39-72e6-457f-acf4-734b91e52182: 'Article Body - Code - Code' # Article Body - Code - Code
    fc6e35f3-4a2a-4b55-ae4a-717059ff4104: Note # Note
    fcdccecf-de72-4e6f-ab6b-df87f08f7622: English # English
    fd18d1cb-d224-448e-8d13-c36f3387c611: Thumbnail # Thumbnail
    fe9ff786-48df-4227-8eda-8476e504fb9e: Globals # Globals
    febbbd03-74e4-49e4-ba70-2a10660683f1: Tags # Tags
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  easymde-markdown-editor:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.4.0
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: $SITE_NAME
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
