fieldLayouts:
  a04b684a-df13-4f54-8b15-deae811f314f:
    tabs:
      -
        elements:
          -
            fieldUid: 90e1e15c-f3ec-4522-999d-401ffa0bcfbb # Site Author
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 69ae30b5-6749-4f94-9283-63027e64b000 # Site Author Email
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e6a58602-4fcb-4319-a14c-053d4b9fd671 # Site Description
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Globals
        sortOrder: 1
handle: globals
name: Globals
sortOrder: 2
