defaultPlacement: end
enableVersioning: true
entryTypes:
  - 924a5c20-68b5-410b-9f04-1a110c403658 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  840ad40c-34ac-4597-8c5f-747198813889: # Scott Gruber
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
