defaultPlacement: end
enableVersioning: true
entryTypes:
  - ce9c5925-d13e-4248-8980-3683d854c4d4 # Notes
handle: notes
maxAuthors: 1
name: Notes
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  840ad40c-34ac-4597-8c5f-747198813889: # Scott Gruber
    enabledByDefault: true
    hasUrls: true
    template: notes/_entry
    uriFormat: '{postDate|date(''Y'')}/{postDate|date(''m'')}/{postDate|date(''j'')}/{slug}'
type: channel
