defaultPlacement: end
enableVersioning: true
entryTypes:
  - afc084fc-aa87-46da-b9b5-d8ef18d375bf # Now
handle: now
maxAuthors: 1
name: Now
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  840ad40c-34ac-4597-8c5f-747198813889: # Scott Gruber
    enabledByDefault: true
    hasUrls: true
    template: now/index
    uriFormat: now
type: single
